<a href="https://colab.research.google.com/github/Sambit1708/DMDW_Lab/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1)** **Download a dataset from kaggle and upload it i google colab and perform any random function.** 

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
root_path = 'gdrive/MyDrive/Colab Notebooks/'

**Import** **Libraries**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv(root_path+'mcu_dataset.csv')

In [ ]:
data.head()

Name US release Date  ... Oscar won Phase
0                            Iron Man     May 2, 2008  ...         0     1
1                 The incredible Hulk   June 13, 2008  ...         0     1
2                          Iron Man 2     May 7, 2010  ...         0     1
3                                Thor     May 6, 2011  ...         0     1
4  Captain America: The first Avenger   July 22, 2011  ...         0     1

[5 rows x 16 columns]

In [ ]:
data.sum().isnull()

Name                False
US release Date     False
Director            False
Producer            False
Duration            False
Genre               False
IMDB rating         False
metascore           False
Cast                False
Budget              False
Domestic Gross      False
Total Gross         False
Opening Gross       False
Oscar Nomination    False
Oscar won           False
Phase               False
dtype: bool

In [ ]:
data.count()

Name                23
US release Date     23
Director            23
Producer            23
Duration            23
Genre               23
IMDB rating         23
metascore           23
Cast                23
Budget              23
Domestic Gross      23
Total Gross         23
Opening Gross       23
Oscar Nomination    23
Oscar won           23
Phase               23
dtype: int64

**2.A) Defining three random array:** 

*1) One dimensional array*

*2) Two dimensional array*

*3) Three dimensional array*

**Use numpy random number generate which we will seed with a set value inorder to ensure  the same random arrays are generated each time when this code is running**

In [ ]:
x1 = []
x2 = [[]]
x3 = [[[]]]
np.random.seed(10)
x1 = np.random.rand(10)
np.random.seed(10)
x2 = np.random.rand(4, 2)
np.random.seed(10)
x3 = np.random.rand( 2,2,2)
print('One-Dimensional Array: ')
print(x1)
print('Two Dimensional Array: ')
print(x2)
print('Three Dimensional Array: ')
print(x3)

One-Dimensional Array: 
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]
Two Dimensional Array: 
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]]
Three Dimensional Array: 
[[[0.77132064 0.02075195]
  [0.63364823 0.74880388]]

 [[0.49850701 0.22479665]
  [0.19806286 0.76053071]]]


**2.B) Display:** 

**1. the ndim (Number of dimension)**

**2. shape (Size of the each dimension)**

**3. size (the total of the array)**

In [ ]:
print('Number of dimension of X1: ',x1.ndim)
print('Number of dimension of X2: ',x2.ndim)
print('Number of dimension of X3: ',x3.ndim)
print('\n')
print('Number of Shape of X1: ',x1.shape)
print('Number of Shape of X2: ',x2.shape)
print('Number of Shape of X3: ',x3.shape)
print('\n')
print('Number of Size of X1: ',x1.size)
print('Number of Size of X2: ',x2.size)
print('Number of Size of X3: ',x3.size)

Number of dimension of X1:  1
Number of dimension of X2:  2
Number of dimension of X3:  3


Number of Shape of X1:  (10,)
Number of Shape of X2:  (4, 2)
Number of Shape of X3:  (2, 2, 2)


Number of Size of X1:  10
Number of Size of X2:  8
Number of Size of X3:  8


**3) Create 2 numpy array named X and Y of integers using range(1-10) and (11-20) command. and create a new array Z by concatinate X and Y.**

In [ ]:
X = np.arange(start=1, stop=10, step=3)
Y = np.arange(start=11, stop=20, step=3)
Z = X+Y
print(X)
print(Y)
print(Z)

[1 4 7]
[11 14 17]
[12 18 24]


**4) Define a 2 dimensional (X2). Concatinate X2 and X2**

In [ ]:
X2 = [[1,2,3],[4,5,6]]
X2 =X2 + X2
print(X2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


**5) create a numpy array of named x range (1 - 10) and perform operations like   x+5, x-5, x/5, x*5, x^2, x%2, logx, log2x, log10x and compute some trigonometric function**b

In [ ]:
x6 = np.arange(1,10)
print('Perform Operation x6 + 5:')
print(x6+5)
print('\n')
print('Perform Operation x6 - 5 ')
print(x6-5)
print('\n')
print('Perform Operation x6 / 5')
print(x6/5)
print('\n')
print('Perform Operation x6 * 5')
print(x6*5)
print('\n')
print('Perform Operation x6 ^ 2 ')
print(x6^2)
print('\n')
print('Perform Operation x6 % 2')
print(x6%2)
print('\n')
print('Perform Operation log(x) ')
print(np.log(x6))
print('\n')
print('Perform Operation log2(x) ')
print(np.log2(x6))
print('\n')
print('Perform Operation log10(x) ')
print(np.log10(x6))
print('\n')
print('Perform Operation sin(x) ')
print(np.sin(x6))
print('\n')
print('Perform Operation cos(x) ')
print(np.cos(x6))
print('\n')
print('Perform Operation log2(x) ')
print(np.tan(x6))
print('\n')

Perform Operation x6 + 5:
[ 6  7  8  9 10 11 12 13 14]


Perform Operation x6 - 5 
[-4 -3 -2 -1  0  1  2  3  4]


Perform Operation x6 / 5
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


Perform Operation x6 * 5
[ 5 10 15 20 25 30 35 40 45]


Perform Operation x6 ^ 2 
[ 3  0  1  6  7  4  5 10 11]


Perform Operation x6 % 2
[1 0 1 0 1 0 1 0 1]


Perform Operation log(x) 
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


Perform Operation log2(x) 
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


Perform Operation log10(x) 
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Perform Operation sin(x) 
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


Perform Operation cos(x) 
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.9111